apiVersion: apps/v1
kind: Deployment
metadata:
  name: wenyan
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wenyan
  template:
    metadata:
      labels:
        app: wenyan
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: WENYAN_LAW_MODE
              value: "{{ .Values.env.WENYAN_LAW_MODE }}"
