services:
  wenyan:
    image: node:20
    command: ["sleep", "infinity"]
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
  minio:
    image: minio/minio
    command: ["server", "/data"]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000"]
